alias ...='cd ../..'
alias ....='cd ../../..'
alias la='ls -A --color=auto'
alias ll='ls -alF --color=auto'
alias l='ls -CF --color=auto'
alias ls='ls --color=auto'
alias rm='rm -i'
alias v='vim'
alias tmux='tmux -2'
alias t='tmux -2'
alias es='exec $SHELL'
alias jquery='curl https://code.jquery.com/jquery-3.2.1.min.js >> jquery.js'
alias q='exit'
